fun main() {
    // Чтение строки ДНК
    val s = "TGGGCAGTAGTAGGTTTGCTAGCTTCAACCCGAAGAGCGGAGACCGAGAGTGAGACGGTATATGTTGTATACAGTGTACAGCACCCGGTGCTACGCCTTGACAGTGCGTCGGTAGACCGATGATACAGAACCTTGAGAGCTTGGTTTTGCGACGGCGTGCGAAATCCCTGGCGTAACGAAATTAAGGCTACCTCAGCCCCTAGATGCTAGAGGAGGCTCTTAAAACAGAGATCGGGGCTCGCCATCGTACGTTGACTAGTGTTTCTGCGTTCGACTCTCATAGAGCGGTTGTAGACCAGGGTCATTCCGGAAGCACCATCCAACCTGAAGAGAACTGGAGATCTGTAGAAGGAAAGACCGGGGTCCCCGGAAAGCCTACTCAGGTTACCTGATAACGGTCGGGTAAATGTCTCACATAGACACTTCGAACGACTAAGTTCACGATCAACAACTGCGTTTGACGCTCGAGTGAGTAATCTTTTGCTCAGAACGGAGAGCCCGAGCTGCTTACTGTCTCGGGTTGCATTGACAGGGTAGAAGCTTAGCTATCATGGGAAGATCGGTCATCGAAGCCCAGTGGGAGAAATTGGATGTCCTGCAGATTTGGCGCGGCGGCCGCAGTGTATCAATTGTACCACTATAACCACCTGGACCGTAGGGCGCTCTCACTAGTTTGGTCATTACAATGAATTATAGTCATGGGTATTCACTTGATCGACGCAAATTGTCTCCACTTTCTGCTACCCCCACCCTTGTTGCTCCAGGTCCCACTACGCTCACTATAAGGGTATCCGGCAGCTCAATTCACTGGAGCGATAGACTGAGAGGCTCAATATCTCTTGACAGCACGAATGCAATC"!!

    // Маппинг для комплементарных символов
    val complement = mapOf('A' to 'T', 'T' to 'A', 'C' to 'G', 'G' to 'C')

    // Разворачиваем строку и заменяем каждый символ на его комплемент
    val reverseComplement = s.reversed().map { complement[it]!! }.joinToString("")

    // Выводим результат
    println(reverseComplement)
}
